namespace chromeftp {
[include="ftpsession.h", async]
callback void FtpSessionConnectCallback();
    
[include="ftpsession.h", async]
callback void FtpSessionErrorCallback(std::string message);
    
[binding_model=by_value, include="ftpsession.h"] class FtpSession {
    FtpSession();
    // ~FtpSession();
    
    void Connect(std::string server, FtpSessionConnectCallback? connectCallback, FtpSessionErrorCallback? errorCallback);
};
}

