[binding_model=by_value, include="ftpsession.h"] class FtpSession {
	FtpSession();
	~FtpSession();

	callback void EmptyCallback();
	callback void ErrorCallback(std::string message);
 
	void Connect(std::string server, EmptyCallback? connectCallback, ErrorCallback? errorCallback);
};


